application: valid-hall-624
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /
  script: main.app

- url: /pusher/auth
  script: pusher_auth.app